- name: apt-get upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  become_user: root

- name: Install Nginx Web Server on Debian Family
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  notify: nginx systemd