- name: Install and configure prometheus
  hosts: prometheus
  become: true
  vars:
    prometheus_version: 2.40.1
    prometheus_targets:
      node:
        - targets:
            - 192.168.1.29:9100
            - 192.168.3.16:9100
          labels:
            type: node_exporter
        - targets:
            - 192.168.1.29:4040
            - 192.168.3.16:4040
          labels:
            type: nginx_logs

  roles:
      - prometheus